### ISSUE TITLE
Can't verify my login

### ISSUE THREAD

**Issue by SamDc73** [syphon-org/syphon#427] opened 2021-12-17 11:45 UTC
form the Element web client i tried to verify my syphon  login, but nothing shows up in my app.
the problem is not form Element end because I verified my nhecko login on my computer.
Using the lastest version on F-droid : 0.2.2
Thanks in advance .

**Comment by 0x1a8510f2** [comment] 2021-12-17 13:53
That feature (cross-signing) is yet to be implemented, I'm afraid. It's planned for version 0.3.0.

Previously, this could still be done by using the "manually verify by text" button on Element but Element has recently removed that feature.

**Comment by notramo** [comment] 2021-12-18 20:32
It isn't removed, it just doesn't work.

**Comment by 0x1a8510f2** [comment] 2021-12-18 20:51
@notramo Element Web has removed "verify by text" in recent versions. Other verification methods, like by emoji or QR code, meanwhile, are not implemented by Syphon.

**Comment by notramo** [comment] 2021-12-18 21:09
It shouldn't be removed, as Hydrogen, Syphon, Cinny and many other clients only provide text verification.
It can't be opened from the Settings panel, but if you open your profile by clicking your avatar in any room, then you can verify the device with text from there.
However, after I compared the keys, and they matched, and clicked OK, the verified client didn't appear as verified, so it's broken.

**Comment by 0x1a8510f2** [comment] 2021-12-18 21:11
I see. That's interesting. I wonder if it's a regression in Syphon or a bug in Element.

>However, after I compared the keys, and they matched, and clicked OK, the verified client didn't appear as verified, so it's broken.

Is that only for Syphon or other clients as well?

**Comment by notramo** [comment] 2021-12-18 21:15
> Is that only for Syphon or other clients as well?

I haven't checked yet. But it shouldn't matter, as it is the task of Element to sign it.

**Comment by notramo** [comment] 2021-12-18 21:17
Possibly related: #435

**Comment by 0x1a8510f2** [comment] 2021-12-18 21:17
Not necessarily. I remember there being an issue where Syphon would incorrectly initialise the session or something (no clue about Matrix encryption stuff) which broke text-based verification. This has since been fixed, but may have regressed.

**Comment by ereio** [comment] 2021-12-19 04:14
I'll check along with #435

**Comment by ereio** [comment] 2021-12-24 13:25
closed by #458

**Closed by ereio** 2021-12-24 13:25 UTC
Labels: bug

**Comment by milahu** [comment] 2022-08-13 08:32
> closed by #458

still an issue in syphon 0.2.13

* element desktop
* verify device
* "To proceed, please accept the verification request on your other device."

... but nothing happens in syphon, running on an old samsung S3 GT-I9300

**Comment by EdGeraghty** [comment] 2022-08-13 11:01
> still an issue in syphon 0.2.13
> 
> * element desktop
> * verify device
> * "To proceed, please accept the verification request on your other device."

Syphon does not yet support interactive session verification. Please [see our FAQ](https://github.com/syphon-org/syphon/blob/dev/docs/faq-en.md) for details on how to find manual verification in Element 

> also #126 is still open

This is because cross-signing is also yet to be implemented.

All of this functionality is roadmapped for our `0.3.0` release
