### ISSUE TITLE
Cannot add room from server other than home server

### ISSUE THREAD

**Issue by e-zk** [syphon-org/syphon#193] opened 2020-11-02 09:30 UTC
I can't seem to add a room that is located on a different home server to my account.  

For instance say I am @person:matrix.org, I can't add #room:tchncs.de via the search for rooms section.

Is this by design? Is there a different way to do it?

Edit: I am on 0.1.4 from F-Droid.

**Comment by ereio** [comment] 2020-11-02 23:16
There was a discussion regarding this in the Syphon matrix room. The issue is somewhere in between a bug and being temporarily overlooked. 

However, the ability to do this will be in the next version (0.1.5) as an extension of the "Search A Topic" screen. The update will let you type in a fully qualified room name to add rooms from any homeserver similar to the way the User Search screen works. Shortly after 0.1.5, an update to that screen will let you search across homeservers.

We'll use this issue to track manual room adding 👍

**Closed** 2021-01-28 04:44 UTC
Labels: bug, enhancement
