### ISSUE TITLE
Toggling "Direct Chat" in chat settings slider broken

### ISSUE THREAD

**Issue by UnixPhonez** [syphon-org/syphon#702] opened 2022-06-27 00:30 UTC
When toggling the direct chat slider under chat settings on a group chat the slider is broken and doesn't want to slide

iPhone X
iOS 15.5

**Comment by dnisbetjones** [comment] 2022-06-27 03:44
Hi there @UnixPhonez, I believe this is expected behaviour as Matrix treats group chats as private rooms rather than direct chats. I will close this for the time being but we can re-open the issue should this be a bug.

Thank you very much for filing an Issue and don't hesitate to do so again in the future. Thanks for trying Syphon!

**Closed by dnisbetjones** 2022-06-27 03:44 UTC

**Comment by notramo** [comment] 2022-07-05 12:33
@dnisbetjones It's not expected behavior. Technically they are the same, but there is a label (`m.direct`), which makes them appear as DM or group.

**Comment by cintek** [comment] 2023-04-22 16:28
There is another case where you could ask yourself why you cannot move the slider. When you create a group chat and are the only user you can't move it. In the logging I can see the reason:
`[ERROR] [toggleDirectRoom] Cannot toggle room to direct without other users`

In these cases it would be better for the usability if the slider would be disabled. And maybe it would also be helpful to show a message to the user.
